name: Update database

on:
  push:
    paths:
      - 'migrations/**'
  workflow_dispatch:

jobs:
  build-site:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      -
        name: Checkout public
        uses: actions/checkout@v3
      -
        name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      -
        name: Install dependencies
        run: npm ci
      -
        name: Update prisma
        run: npx keystone prisma migrate deploy

